import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";

import { describe, expect, it } from "vitest";

/**
 * Guard against auto-generated barrel files.
 *
 * An IDE extension in this project keeps generating `index.ts` files that
 * re-export everything in their directory. They have broken `npm run typecheck`
 * three times: they re-export route handlers (duplicate GET/POST), they point
 * at directories with no module, and they collide on names exported by two
 * different modules.
 *
 * Nothing in this codebase imports from a barrel — every import is a direct
 * path — so these files are pure liability. Deleting them only resets the
 * clock; this test is the part that actually holds, because it fails the suite
 * the moment one reappears.
 *
 * If a barrel is ever genuinely wanted, add its path to ALLOWED with a comment
 * saying why. Do not delete this test.
 */

const SRC = join(process.cwd(), "src");

/** Paths (relative to src/, POSIX separators) that may be barrels. */
const ALLOWED = new Set<string>([]);

/** A file whose every non-blank line is `export * from '...'` or similar. */
function isBarrel(contents: string): boolean {
  const lines = contents
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("//"));

  // An empty index.ts is the degenerate case the generator also produces, and
  // it breaks typecheck with "is not a module" the moment something re-exports
  // it. Treat it as a barrel too.
  if (lines.length === 0) return true;

  return lines.every((line) => /^export \* from ['"][^'"]+['"];?$/.test(line));
}

function findIndexFiles(dir: string, found: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (entry === "node_modules" || entry.startsWith(".")) continue;

    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      findIndexFiles(full, found);
    } else if (entry === "index.ts" || entry === "index.tsx") {
      found.push(full);
    }
  }
  return found;
}

describe("no auto-generated barrel files under src/", () => {
  it("finds none", () => {
    const offenders = findIndexFiles(SRC)
      .filter((file) => isBarrel(readFileSync(file, "utf8")))
      .map((file) => relative(SRC, file).split(sep).join("/"))
      .filter((rel) => !ALLOWED.has(rel));

    expect(
      offenders,
      offenders.length > 0
        ? `Barrel index files reappeared:\n  ${offenders.join("\n  ")}\n\n` +
            "These are generated by an IDE extension and break typecheck. " +
            "Delete them and turn the extension off — see the README's " +
            "Troubleshooting section."
        : undefined,
    ).toEqual([]);
  });
});
