/**
 * src/lib/ai/responsibleAI.ts
 *
 * Disclaimer and responsible-AI text constants for all AI features in Storyverse.
 *
 * Firdosi's UI renders these strings next to every AI-generated panel or proposal.
 * Keeping them in one file means any required wording change (legal, policy, etc.)
 * is made in exactly one place.
 *
 * No runtime dependencies — import freely from components.
 */

// ---------------------------------------------------------------------------
// Per-feature disclaimer text
// ---------------------------------------------------------------------------

/**
 * Shown next to every continuity-review result.
 * Emphasises that the model may miss issues and human review is required.
 */
export const CONTINUITY_REVIEW_DISCLAIMER =
  "This continuity review was generated by the configured AI model " +
  "and may contain errors or omissions. It is provided as a writing aid only. " +
  "A human editor must approve or dismiss every finding before any scene is locked.";

/**
 * Shown next to every merge-assistant proposal.
 * Makes explicit that the AI cannot and will not execute any merge.
 */
export const MERGE_ASSISTANT_DISCLAIMER =
  "These merge strategies are an AI-generated preview. No changes have been made to your story. " +
  "You must select a strategy and confirm the merge manually. " +
  "The AI does not have write access to your canon timeline.";

/**
 * Shown next to every character-refinement proposal.
 * Reinforces that the proposal must be explicitly approved before any record changes.
 */
export const CHARACTER_REFINE_DISCLAIMER =
  "This character update is an AI-generated proposal. Your locked character record has not been changed. " +
  "Review the proposed description and generation instruction carefully, " +
  "then approve or discard before applying.";

/**
 * Shown in the panel viewer alongside every AI-generated or fallback panel image.
 * Covers both the real model output and the deterministic fallback asset.
 */
export const PANEL_GENERATION_DISCLAIMER =
  "This prototype shows prepared panel artwork; it does not call a live image model. " +
  "The assembled request is displayed so creators can review the locked canon facts, " +
  "character description, and style constraints that a future image pipeline would receive. " +
  "Human approval is required before any image is added to the published story.";

// ---------------------------------------------------------------------------
// General / shared text
// ---------------------------------------------------------------------------

/**
 * Short one-line badge label shown on any AI-produced content block.
 * Use in aria-labels, tooltips, and status badges.
 */
export const AI_GENERATED_LABEL = "AI-generated — requires human review";

/**
 * Short one-line badge label for the deterministic fallback / mock path.
 * Indicates the real model was not called.
 */
export const AI_FALLBACK_LABEL = "Demo preview — AI model not called";

/**
 * Link to a provider-neutral responsible AI framework for "Learn more" anchors.
 * External URL — safe to use in <a href>.
 */
export const RESPONSIBLE_AI_URL =
  "https://www.nist.gov/itl/ai-risk-management-framework";

// ---------------------------------------------------------------------------
// Aggregate object — convenient for rendering a complete disclaimer block
// ---------------------------------------------------------------------------

export const RESPONSIBLE_AI_DISCLAIMERS = {
  continuityReview: CONTINUITY_REVIEW_DISCLAIMER,
  mergeAssistant: MERGE_ASSISTANT_DISCLAIMER,
  characterRefine: CHARACTER_REFINE_DISCLAIMER,
  panelGeneration: PANEL_GENERATION_DISCLAIMER,
} as const;

export type ResponsibleAIFeature = keyof typeof RESPONSIBLE_AI_DISCLAIMERS;
